// Provides a random sample essay

const essays = [

    `Richmond Beach was my spiritual hangout in my childhood. It is a rocky beach in the city of Richmond Beach, which can be accessed by a long downhill drive (by car or bicycle) from the city of Edmonds. Or, as I did often, took the 30-minute walk from my house to the calm waters through a tranquil stroll through the woods of Woodway. It used to be a place inhabited by Native Americans, but now it is occupied by mostly Caucasian people. However, a totem pole stands in tribute to the tribes that used to call the beach home. It has a vast property, with a beach, a playground, two upper lawns for the view and recreation, myriad “secret” trails along the clay hillsides, picnic areas, and a square where people can walk around, take an outdoor rinse-shower after a swim, and benches for the spectacular view.

With the sagebrush, chattering birds, train tracks, the croak of frogs, wind, herons, various shells, a cave along the beach, and a fantastic view of the Olympic Mountains, Richmond Beach is at once ordinary and extraordinary. Being there brings you into another state, in which you want to introspect, be calm, and be positive.

In high school, I was not a very social person. I did not have so many friends, and I did not feel like I belonged in a group most of the time. But when I went to Richmond Beach, these worries were left behind. It seemed like a mystical place to me, and in a way, it still does.

I would walk to various places on the beach: a secret cave in the clay hills on the left, the train tracks that lead all the way from Seattle to Chicago, the mass of sagebrush where the melody of birds made for a serene scene, and of course the beach itself, which was scattered with shells, tide pools, crabs, seals, driftwood, remnants of parties, and more.

The passing trains always attracted me there as well. My first word was “choo choo,” since the first three years of my life was near a train station in the Greenlake area of Seattle. So, I had a calling towards trains since my birth. Walking the tracks, I would meet interesting people, learn to know when trains were coming through the vibration and singing of the rails, and would be immersed in a world with a forest on one side and the Puget Sound and the other. This combination of forest and ocean was enchanting, and captured my imagination.

I wrote many poems about this place, and have been continually inspired by the atmosphere there. In fact, my poetry has developed largely at Richmond Beach. No where else have I written so many poems—except perhaps on public transport. I started writing lyrical and narrative poetry around 11 years of age, and have continued since. For the past few years, I have been writing almost exclusively haiku. A lot of my haiku is inspired by the nature of Richmond Beach, how I relate to it spiritually, and by the people who used to occupy that land—as I feel a special connection with Native Americans.

It seems that Richmond Beach is one of those places that no matter how bad you feel, you will leave feeling soothed and renewed. It is like therapy just to walk around, feel the ionic breeze of the Puget Sound, smell the seaweed and moisture, hear the variety of birds singing, listen to the crashing of moderate waves, witness the sailboats and other boats on the water, take in the Olympic mountains in all their glory, see people enjoying themselves on the beach, the whistle and trucking of a distant train, and feel the sand on the soles of your feet, melding into each other with each step. It is a whole therapeutic package.

It will be hard to ever forget Richmond Beach. It is now intertwined in my poetry, childhood, spiritual life, family life, romantic memories, and even the passing of my father, whose ashes was spread there. So, whenever I visit Richmond Beach, all of these elements rest in my mind and soul. There are other places that stir my imagination and supply me with sentimental rushes, but Richmond Beach is at the top of my list.`
    ,

    `    “Mother died today. Or maybe, yesterday; I can't be sure.” This is the opening to a novel entitled “The Stranger” by renowned French-Algerian philosopher Albert Camus (1913-1960A.D.) through the narration of the main protagonist, Meursault. Camus, like many of his contemporaries including key figures like Jean-Paul Sartre, Friedrich Nietzsche, and Søren Kierkegaard, grappled with the disheartening realization that there is no pre-ordained meaning in life, in light of a God that seems ever dissipating from the collective psyche. His novel, “The Stranger”, while by no means an autobiography, offers us a window into Camus’ existentialist outlook through Meursault, a character that is sentenced to death for his mere indifference to a murder he committed, an indifference that he feels for all things, including his death. Although a fascinating character, Meursault’s mindset that nothing matters is not only unproductive, it is detrimental to any conception of fulfilling life. Meursault expresses many aspects of Camus’ outlook, however, it is in their respective attitudes toward existence in which they differ. While Camus accepts the absurdity of existence, he resists nihilism or destitution in favor of a more stoic and optimistic angle on existence; it is this much more fruitful perspective that disconnects Camus from the notion that enduring life is pointless, giving one the opportunity to create their own meaning and purpose.
    Since the times of ancient Greece, great thinkers such as Plato and Aristotle believed that everything had an essence, a certain set of core properties that are necessary or essential for a thing to be what it is. Because the essence of a thing is necessary for its existence, the logic goes, it must precede existence. Essentialism claims that the ontology, and subsequently purpose of all things, including humans, were determined by its essence. In “The Stranger”, Meursault rejects this essentialism and its promise of divine meaning. Meursault, in his atheism, believes that there is no preordained purpose in anything, and grasps his insignificance in the cold, silent indifference of reality. 
    Meursault is a depiction of the state of mind defined by sociologist Émile Durkheim (1858-1917A.D.) as anomie, a condition in which through alienation, society provides little moral guidance to the individual. It is this realization of futility that gives way to his apathy toward life: his refusal to lie, his inability to feel genuine emotion, his disregard for social norms, his refusal to hide his feelings, and his abstinence from judgment. Meursault is hopelessly dissatisfied with the explanations for socially held beliefs and values. He recognizes sentimentality as people creating meaning in a world with no inherent meaning. In many ways, society is threatened by his mere existence, as its very pillars rest on the idealistic acceptance of human creation as divine order, such as objective morality, justice, or love. Meursault, in a sense, is the expression of Camus’ realization of the extent of his insignificance and the lack of inherent meaning, or essence. He is a result of Camus tackling the problem of a reality with no preordained meaning and its implications on popular belief. Meursault came to the conclusion that the idea of meaning itself had no place in existence, and that what people understand it to be is a man-made illusion, a cry for purpose where there is no roadmap, no end goal.
    There is, however, a distinction to be made. While Camus didn’t believe in preordained meaning, he did accept meaning as a construct of the human intellect. He believes we have to carry through life knowing that our efforts will be largely futile, our future generations hopelessly corrupt and violent, and our lives soon forgotten, yet we must endure nonetheless. Camus compares this to the tale of Sisyphus, the man condemned to push a boulder up a hill only to watch it roll back down in perpetuity.
    While Meursault’s notion that life is meaningless is certainly bleak and unforgiving, it is merely a part of Camus, a representation of the outcome of the complete rejection of essence. When one digs deeper into the beliefs and motivations of Camus, a much more optimistic proposition appears. He states that we must acknowledge the meaninglessness and absurdity of existence, and yet triumph in finding meaning where there is none. Camus, through this process, often writes profoundly about topics such as friendship, food, nature, sunshine, dancing, and intimacy. When one recognizes the absurdity of reality they are on the verge of despair, perhaps, but also compelled to live life more passionately. Pertaining to Camus’ famous piece of advice, one must imagine Sisyphus happy.`
    ,
    `Airport security in America is often a topic of contention. Ever since airport screenings were nationalized, many have characterized it by long lines, its often questionable invasions of privacy, and its strange procedures including tightly regulating the amounts of liquid allowed in carry-on and mandating that passengers take off their shoes during screenings. Many proponents of federal airport security state that these downsides are a necessary evil in order to ensure the safety of passengers. However, evidence suggests that the TSA is not only inefficient but also a massive burden on the taxpayer and the cause systematic invasions of privacy, all for results measurably worse than that of private contractors; it is in the nation's best interest that airport security be privatized.
    The current structure of airport security is quite recent in the history of American aviation. Before the turn of the century, it was the responsibility of airports to provide security, usually by contracting a private company. However, the Aviation and Transportation Security Act of 2002 (a response to the September 11’th attacks) ruled that all passenger screenings must be conducted by federal employees. The federal agency tasked with handling this challenge was the Transportation Security Administration (TSA), the government organization responsible for screenings at a vast majority of airports in the United States today.
    Not all American airports have federal security, however. According to David Inserra of the Heritage Institute, the U.S. allows airports to opt-out of TSA-run screening through the Screening Partnership Program (SPP). One of the outliers within American airport security is that of San Francisco International Airport, whose screenings are handled by a private contractor as a result of the SPP. The security of its Californian counterpart LAX, on the other hand, is handled by the TSA. In a study by the House Transportation and Infrastructure Committee, the screening process at San Francisco International Airport was found to be as much as 65% more efficient on a per-passenger basis when compared to the federal screening process in Los Angeles (Inserra). 
    While the San Francisco International Airport is often touted for its comparatively swift and seamless screening process, the lines at airports with government-run screenings keep getting longer, as exemplified by the TSA gradually increasing its recommended check-in time to 3 hours before departure. The Port Authority of New York and New Jersey, who collectively control the LaGuardia and JFK International airports, described the TSA’s screening process as “abysmal” (Jancer). Many other airports look to private contractors for screenings, however, “barriers to using the [SPP] have prevented its wider adoption” (Inserra).
    As a consequence of inefficient processes and management, as well as complications that arise with government initiatives at the scale of the TSA, federally provided airport security is more costly. The same study by the House Transportation and Infrastructure Committee estimated that “San Francisco’s SPP model could save Los Angeles and other major airports 42 percent of their screening costs” (Inserra).
    Other issues with the current state of airport security are much more personal. TSA procedures oftentimes include unwarranted invasions of personal privacy. Usually, these are in the form of “X-ray” tools and patdown procedures. In an article for NBC, a former TSA employee admitted that employees tasked with reviewing body-scan images often joked with each other about passengers’ “weight, attractiveness, and penis and breast sizes” and would retaliate against rude passengers by making them wait longer. Despite the thousands of reports of misconduct by TSA agents abusing procedure, the TSA has yet to alter their process.
    In the face of such criticisms, it is quite normal for one to assume that while the TSA is at times inefficient, costly and overly-stringent, it gets the job done. Sadly, because of little oversight and a lack of performance-based incentives, the TSA has no obligation to do its job. An internal investigation conducted by the Department of Homeland Security attempted passing 70 banned weapons and explosives through TSA screenings. Of the 70, a measly 3 were caught, leaving the TSA with a success rate of 5% (Bradner). Furthermore, nearly every study performed shows that private screeners “are at least as good as, if not better than, government screeners at detecting security threats” (Inserra).
    Why would a screening organization be so much more arduous, expensive, and time-consuming yet have the same, if not worse results? Twentieth-century Austrian economist Friedrich Hayek (1899-1992) points to central planning as the root cause. In a free-market economy, organizations have an inherent obligation to provide the highest possible quality of goods and services with minimal resources spent. If a company’s goods or services are less valuable to consumers than the resources spent to produce it, the company involved will be punished financially.
    In the case of privatized aviation screenings, airports are consumers voluntarily paying for the services of security contractors; therefore, if a private contractor fails to deliver adequate security, the contractor can be easily replaced because the free market fosters competition that constantly forces organizations to adapt. The same cannot be said about the TSA. Bouts of government/central planning have neither the direct monetary incentive to produce adequate services nor the encouragement to reduce costs; it is funded not through ingenuity or effectiveness, but by means of government force.
        … and [the free market] regards competition as superior not only because in most circumstances it is the most efficient method known but because it is the only method which does not require the coercive or arbitrary intervention of authority. (Hayek, 45)
    While a private contractor must evolve procedures based on the needs of both airports and travelers in order to stay in business, government-run, centrally planned airport security is funded involuntarily by taxpayers and therefore has no such obligation.
        Another aspect of central authority is its inability to cater to the complexities that naturally arise in a national under-taking on the scale of American aviation.
    As the factors which have to be taken into account become numerous and complex, no one center can keep track of them. The constantly changing conditions of demand and supply of different commodities can never be fully known or quickly enough disseminated by any one center. (Hayek, 59)
    Sadly, much of the decisions made by the TSA are characterized by poor management of resources. According to Mike Ahlers and Rene Marsh of CNN Politics, a report from the Department of Homeland Security indicated that the TSA had 17,000 items with an estimated cost of $185.7 million stored in its warehouses in 2012 without any plans of use or relocation, shedding light on blatant mismanagement of federal funds by senior staff. Furthermore, a separate investigation found the organization to place many high salary criminal investigators to remedial tasks, wasting millions each year (Ahlers). The federally run airport security is effectively immune to the punishment of bad practices inherent in a free-market; the TSA provides bad security and taxpayers have to pay handsomely. The current annual budget for the agency is well over $7 billion, and it has no plans to reduce that price tag (Schneier).
        While there is no doubt that the TSA was a well-intentioned response to a national catastrophe in a time of public unrest, over time it has consistently failed the people it was established to protect. Federally managed airport security is costly, burdensome, ineffective, and unwilling to improve. A careful look at the TSA and its effects can leave a person with only one conclusion: the public deserves private airport security.`
]

export default function getSampleEssay() {
    return essays[Math.floor(Math.random() * essays.length)];
}