// Provides a random sample essay

const essays = [

    `Richmond Beach was my spiritual hangout in my childhood. It is a rocky beach in the city of Richmond Beach, which can be accessed by a long downhill drive (by car or bicycle) from the city of Edmonds. Or, as I did often, took the 30-minute walk from my house to the calm waters through a tranquil stroll through the woods of Woodway. It used to be a place inhabited by Native Americans, but now it is occupied by mostly Caucasian people. However, a totem pole stands in tribute to the tribes that used to call the beach home. It has a vast property, with a beach, a playground, two upper lawns for the view and recreation, myriad “secret” trails along the clay hillsides, picnic areas, and a square where people can walk around, take an outdoor rinse-shower after a swim, and benches for the spectacular view.

    With the sagebrush, chattering birds, train tracks, the croak of frogs, wind, herons, various shells, a cave along the beach, and a fantastic view of the Olympic Mountains, Richmond Beach is at once ordinary and extraordinary. Being there brings you into another state, in which you want to introspect, be calm, and be positive.
    
    In high school, I was not a very social person. I did not have so many friends, and I did not feel like I belonged in a group most of the time. But when I went to Richmond Beach, these worries were left behind. It seemed like a mystical place to me, and in a way, it still does.
    
    I would walk to various places on the beach: a secret cave in the clay hills on the left, the train tracks that lead all the way from Seattle to Chicago, the mass of sagebrush where the melody of birds made for a serene scene, and of course the beach itself, which was scattered with shells, tide pools, crabs, seals, driftwood, remnants of parties, and more.
     
    The passing trains always attracted me there as well. My first word was “choo choo,” since the first three years of my life was near a train station in the Greenlake area of Seattle. So, I had a calling towards trains since my birth. Walking the tracks, I would meet interesting people, learn to know when trains were coming through the vibration and singing of the rails, and would be immersed in a world with a forest on one side and the Puget Sound and the other. This combination of forest and ocean was enchanting, and captured my imagination.
    
    I wrote many poems about this place, and have been continually inspired by the atmosphere there. In fact, my poetry has developed largely at Richmond Beach. No where else have I written so many poems—except perhaps on public transport. I started writing lyrical and narrative poetry around 11 years of age, and have continued since. For the past few years, I have been writing almost exclusively haiku. A lot of my haiku is inspired by the nature of Richmond Beach, how I relate to it spiritually, and by the people who used to occupy that land—as I feel a special connection with Native Americans.
    It seems that Richmond Beach is one of those places that no matter how bad you feel, you will leave feeling soothed and renewed. It is like therapy just to walk around, feel the ionic breeze of the Puget Sound, smell the seaweed and moisture, hear the variety of birds singing, listen to the crashing of moderate waves, witness the sailboats and other boats on the water, take in the Olympic mountains in all their glory, see people enjoying themselves on the beach, the whistle and trucking of a distant train, and feel the sand on the soles of your feet, melding into each other with each step. It is a whole therapeutic package.
    
    It will be hard to ever forget Richmond Beach. It is now intertwined in my poetry, childhood, spiritual life, family life, romantic memories, and even the passing of my father, whose ashes was spread there. So, whenever I visit Richmond Beach, all of these elements rest in my mind and soul. There are other places that stir my imagination and supply me with sentimental rushes, but Richmond Beach is at the top of my list.`
    ,

    `“Mother died today. Or maybe, yesterday; I can't be sure.” This is the opening to a novel entitled “The Stranger” by renowned French-Algerian philosopher Albert Camus (1913-1960A.D.) through the narration of the main protagonist, Meursault. Camus, like many of his contemporaries including key figures like Jean-Paul Sartre, Friedrich Nietzsche, and Søren Kierkegaard, grappled with the disheartening realization that there is no pre-ordained meaning in life, in light of a God that seems ever dissipating from the collective psyche. His novel, “The Stranger”, while by no means an autobiography, offers us a window into Camus’ existentialist outlook through Meursault, a character that is sentenced to death for his mere indifference to a murder he committed, an indifference that he feels for all things, including his death. Although a fascinating character, Meursault’s mindset that nothing matters is not only unproductive, it is detrimental to any conception of fulfilling life. Meursault expresses many aspects of Camus’ outlook, however, it is in their respective attitudes toward existence in which they differ. While Camus accepts the absurdity of existence, he resists nihilism or destitution in favor of a more stoic and optimistic angle on existence; it is this much more fruitful perspective that disconnects Camus from the notion that enduring life is pointless, giving one the opportunity to create their own meaning and purpose.

    Since the times of ancient Greece, great thinkers such as Plato and Aristotle believed that everything had an essence, a certain set of core properties that are necessary or essential for a thing to be what it is. Because the essence of a thing is necessary for its existence, the logic goes, it must precede existence. Essentialism claims that the ontology, and subsequently purpose of all things, including humans, were determined by its essence. In “The Stranger”, Meursault rejects this essentialism and its promise of divine meaning. Meursault, in his atheism, believes that there is no preordained purpose in anything, and grasps his insignificance in the cold, silent indifference of reality. 
    
    Meursault is a depiction of the state of mind defined by sociologist Émile Durkheim (1858-1917A.D.) as anomie, a condition in which through alienation, society provides little moral guidance to the individual. It is this realization of futility that gives way to his apathy toward life: his refusal to lie, his inability to feel genuine emotion, his disregard for social norms, his refusal to hide his feelings, and his abstinence from judgment. Meursault is hopelessly dissatisfied with the explanations for socially held beliefs and values. He recognizes sentimentality as people creating meaning in a world with no inherent meaning. In many ways, society is threatened by his mere existence, as its very pillars rest on the idealistic acceptance of human creation as divine order, such as objective morality, justice, or love. Meursault, in a sense, is the expression of Camus’ realization of the extent of his insignificance and the lack of inherent meaning, or essence. He is a result of Camus tackling the problem of a reality with no preordained meaning and its implications on popular belief. Meursault came to the conclusion that the idea of meaning itself had no place in existence, and that what people understand it to be is a man-made illusion, a cry for purpose where there is no roadmap, no end goal.
    
    There is, however, a distinction to be made. While Camus didn’t believe in preordained meaning, he did accept meaning as a construct of the human intellect. He believes we have to carry through life knowing that our efforts will be largely futile, our future generations hopelessly corrupt and violent, and our lives soon forgotten, yet we must endure nonetheless. Camus compares this to the tale of Sisyphus, the man condemned to push a boulder up a hill only to watch it roll back down in perpetuity.
    
    While Meursault’s notion that life is meaningless is certainly bleak and unforgiving, it is merely a part of Camus, a representation of the outcome of the complete rejection of essence. When one digs deeper into the beliefs and motivations of Camus, a much more optimistic proposition appears. He states that we must acknowledge the meaninglessness and absurdity of existence, and yet triumph in finding meaning where there is none. Camus, through this process, often writes profoundly about topics such as friendship, food, nature, sunshine, dancing, and intimacy. When one recognizes the absurdity of reality they are on the verge of despair, perhaps, but also compelled to live life more passionately. Pertaining to Camus’ famous piece of advice, one must imagine Sisyphus happy.`
    
]

export default function getSampleEssay() {
    return essays[Math.floor(Math.random() * essays.length)];
}